src/main.cpp, src/mdimainwindow.cpp, src/mdimainwindow.h, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/preferencesdialog.h, ui/mdimainwindow.ui, ui/preferencesdialog.ui
Connected Gui from preferences dialog to classes
=> Preferences - connective tissue

src/consts.h, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/preferencesdialog.h
Putting all global constants in the same place
=> Moved constants to const.h

src/configureperchanpriodlg.cpp, src/gridwidget.cpp, src/gridwidget.h, src/priorityeditwidget.cpp, src/universedisplay.cpp
=> Transmit devel

src/preferencesdialog.cpp, src/preferencesdialog.h, ui/preferencesdialog.ui
Dialog was saving immediately to Preferences class.
added member variables and save function that is applied when {Save} is
selected from button box.
=> Fixed preferencesdialog .cpp and .h to allow "cancel"

sACNView.pro, src/aboutdialog.cpp, src/aboutdialog.h, src/preferences.h, src/preferencesdialog.cpp, src/scopewidget.cpp, src/scopewidget.h, src/scopewindow.cpp, src/scopewindow.h, ui/aboutdialog.ui, ui/scopewindow.ui
=> Scope Work

sACNView.pro, src/mergeduniverselogger.cpp, src/mergeduniverselogger.h, src/universeview.cpp, src/universeview.h, ui/universeview.ui
Implemented sACNView v1 formatted Log To File function in universe view
=> Log to file

sACNView.pro, src/nicselectdialog.cpp, src/preferencesdialog.cpp, src/sacn/sacnlistener.cpp, src/snapshot.h
Found a few compiler warnings and other things as I built against MSVC2015.
=> Couple of tiny things

install/linux/sACNView.dbp
Config file for Debreate (https://antumdeluge.github.io/debreate-web/)
ZIPed up .deb package for Beta 2 here:
[sACNView_2.0.0-Beta-2_amd64.zip](https://github.com/docsteer/sacnview/files/923949/sACNView_2.0.0-Beta-2_amd64.zip)
=> Linux (Debian/Ubuntu) installer config

src/sacn/sacneffectengine.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnuniverselistmodel.cpp, src/transmitwindow.cpp
Resolves #25 
Universe tree overview does not select correct NIC 
Resolves #26 
Closing an active transmit window crashes application
=> Resolves #25 and #26

src/mdimainwindow.cpp, src/sacn/sacnuniverselistmodel.cpp
Allow user to type a value upto MAX_SACN_UNIVERSE.
Also allow spin down below 1 (Wrapping)
Input is saitised down to legitimate displayable range
=> GUI Tweak to universe list spin box

ui/nicselectdialog.ui
Don't make "Work Offline" the default button when a NIC has been selected!
=> Network select dialog

src/preferences.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/sacn/sacnuniverselistmodel.cpp, src/sacn/streamcommon.h, src/transmitwindow.cpp, src/transmitwindow.h, src/universeview.cpp, src/universeview.h, ui/universeview.ui
Preview data options where not respected and preview info was not exposed to the user.
=> Update to preview mode

src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsocket.cpp, src/sacn/sacnsocket.h, src/sacn/sacnuniverselistmodel.cpp, src/sacn/sacnuniverselistmodel.h, src/universeview.cpp, ui/preferencesdialog.ui
Updates to socket binding to ensure correct interface is selected
Updates to improve cross compatibility
Resolves #21 and similar issues across other platforms *Requires QT => 5.9*
=> Socket binding and Cross platform compatibility

src/sacn/sacnuniverselistmodel.cpp, src/sacn/sacnuniverselistmodel.h
It was possiable to change universes while processing a packet for the old one
=> Mutex on universe change

src/aboutdialog.cpp, src/main.cpp, src/multiuniverse.cpp, src/sacn/sacneffectengine.cpp, src/sacn/sacneffectengine.h, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/sacn/sacnsocket.cpp, src/sacn/streamingacn.cpp, src/transmitwindow.cpp
Using QT native features for memory management
=> Threadsafe shutdown of windows and application

sACNView.pro, src/logwindow.cpp, src/logwindow.h, src/mdimainwindow.cpp, src/mdimainwindow.h, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/universeview.cpp, src/universeview.h, ui/logwindow.ui, ui/universeview.ui
Add log window which records changes live
=> Add Log Window

src/multiuniverse.cpp, src/multiuniverse.h, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/snapshot.cpp, src/snapshot.h, src/transmitwindow.cpp, src/transmitwindow.h
Add timeout handling in sACNSender, and handling on the UI side to show
sources timing out.
=> Implement timeouts

src/main.cpp, src/mdimainwindow.cpp, src/mdimainwindow.h, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/transmitwindow.cpp, src/transmitwindow.h, ui/preferencesdialog.ui
=> Add saving of presets and restore of window geometry option

src/sacn/sacnsender.cpp
Correctly define an if statements scope
=> Ambiguous scope

sACNView.pro, src/aboutdialog.cpp, ui/aboutdialog.ui
About window formatting is consistant 
GIT_DATE defines split to improve cross platform and compiler compatibility
=> About window formatting and Cross platform (and compiler) work

sACNView.pro, src/aboutdialog.cpp, src/mdimainwindow.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsender.cpp, src/sacn/sacnsocket.cpp, src/sacn/sacnuniverselistmodel.cpp, src/sacn/sacnuniverselistmodel.h, src/sacn/streamingacn.cpp, src/sacn/streamingacn.h, ui/aboutdialog.ui
Universe view uses main pool of sockets
Unicast data is always handled
Fixes #47 #48 #49 #50
=> Socket pool improvements

src/sacn/sacnlistener.cpp
Priority 0 was not merged in RX display
=> RX Merge priority 0

src/main.cpp
Define QT_AUTO_SCREEN_SCALE_FACTOR
=> Scale nicely on high DPI displays

src/transmitwindow.cpp
Uncheck the record preset button when a new preset has been recorded
=> Uncheck record preset button

src/sacn/sacnuniverselistmodel.cpp, src/sacn/sacnuniverselistmodel.h
Ensure that a source isn't removed as it's being added
Possible resolution to #68
=> Create mutex on source change

src/sacn/sacneffectengine.cpp
Clear output buffer when an effect changes and correctly clear last address on a range chase
Resolves #64
=> Effect buffer clears

sACNView.pro, src/bigdisplay.cpp, src/bigdisplay.h, src/gridwidget.cpp, src/gridwidget.h, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/universeview.cpp, src/universeview.h, ui/bigdisplay.ui
Resolves #57 by adding a big display window to monitor a single 8bit/16bit/rgb address(s) on a large display
=> Add big display

sACNView.pro, src/main.cpp, src/versioncheck.cpp, src/versioncheck.h
Check git hub for a newer version on start
=> New version check

src/transmitwindow.cpp
Will allow you to enter numbers between 490 and 512, and then change this to 489.
Previous behavior was hard limit to 489
In response to #72
=> Nicer handling of start address numbers in TX

src/sacn/sacnuniverselistmodel.cpp
The previous change #69 was a bit flawed
Resolves #68
=> Better handling of mutex

.travis.yml, install/linux/_FPM_Makefile
=> [Travis] Create .deb

src/main.cpp, src/nicselectdialog.cpp, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, ui/mdimainwindow.ui
Better checking of suitiable interfaces
WIll ask user on start if previous interface is now not suitiable (i.e. Offline, no IP, etc).
Selected interface is show in main window status bar
=> Better interface checking and display

.gitignore, .travis.yml, install/linux/usr/share/applications/sacnview.desktop, sACNView.pro
Roll in #85 with specific project fixes
=> Include architecture in AppImage filename by using default naming scheme

src/mdimainwindow.cpp, src/mdimainwindow.h, src/multiuniverse.cpp, src/multiuniverse.h, src/scopewindow.cpp, src/scopewindow.h, src/snapshot.cpp, src/snapshot.h, src/transmitwindow.cpp, src/transmitwindow.h, src/universeview.cpp, src/universeview.h
Use the selected universe from the tree as a default for the sub-window widgets
=> Use Selected Universe

ui/mdimainwindow.ui
=> Spinbox correction

docs/index.md
Add Supported Platforms to website
=> Webpage: Supported Platforms

src/gridwidget.cpp, src/gridwidget.h, src/sacn/sacnlistener.h, src/universedisplay.cpp, src/universedisplay.h, src/universeview.cpp, ui/universeview.ui
GridView scaling is a bit naiive, this doesn't handle the aspect ratio change very well.
=> Universe View now optionally displays channel priorities

sACNView.pro
=> [Linux] Filename fix

docs/_layouts/default.html, src/sacn/firewallcheck.cpp, src/sacn/sacnlistener.cpp
Resolves another, and hopefully final, cause of #68
Removes redunent code and addes debug messaging to the fix for #104
=> Resolves #68 and adds debug to fix for #104

docs/_layouts/default.html, docs/assets/css/style.scss, docs/index.md
- Make buttons layout 4 wide
- Fix support for older IE versions
=> Website fixes

src/snapshot.cpp, src/snapshot.h, ui/snapshot.ui
Request from Abby -  make sources able to be enabled/disabled on an
individual basis in snapshot
=> Add Snapshot per-source enable/disable functionality

src/consts.h
No pending issues from v2.0.1-RC3 propose release
=> v2.0.1 Release

src/main.cpp, ui/mdimainwindow.ui
Possible fix for #115, however unable to fully test!
=> Possible fix for #115

sACNView.pro, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/sacn/e1_11.h, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/sacn/streamcommon.cpp, src/sacn/streamcommon.h, src/sacn/streamingacn.cpp, ui/preferencesdialog.ui
Respect draft flag on dd packets (#142)
Don't check non-draft option bits on draft packets!
=> Draft sACN fixes

src/gridwidget.cpp
Possible solution to display gird #131
=> Universe display grid ignores aspect ratio

README.md
=> Small corrections to README

sACNView.pro, src/commandline.cpp, src/commandline.h, src/multiuniverse.cpp, src/qt56.h, src/transmitwindow.cpp, ui/transmitwindow.ui
Added minus, offset, thru thru
Example: [1] [Thru] [5][1][2] [-] [100] [@] [Full]
Results in all addresses at full, except address 100
Example: [1] [thru] [1][0][0] [offset] [3] 
Selects every third address
Example: [1] [thru] [thru] 
Selects 1 thru 512
Resolves #152
=> Offset and minus

src/consts.h
Feature request #172, add some more fade rates. Easiest ever :)
=> Add Additional FX rates

src/mdimainwindow.cpp, src/mdimainwindow.h, src/sacn/sacndiscoveredsourcelistmodel.cpp, src/sacn/sacndiscoveredsourcelistmodel.h, src/sacn/sacndiscovery.cpp, src/sacn/sacnuniverselistmodel.cpp
Fixes a couple of debugging assert fails in the ItemModel for source discovery.
=> Fix Debug ASSERT fails

src/clssnapshot.cpp, src/clssnapshot.h, src/gridwidget.cpp, src/snapshot.cpp, src/snapshot.h, ui/snapshot.ui
Add an overall indicator for snapshot window
=> Add overall Snapshot match indicator

src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp
=> Recall saved interfaces on name and mac, then by mac

install/win/install.nsi, sACNView.pro, ui/aboutdialog.ui
Use www.sacnview.org for appropriate links
=> www.sacnview.org

src/main.cpp, src/nicselectdialog.cpp, src/preferences.cpp, src/preferencesdialog.cpp
If last selection was localhost/offline, then nic selection dialog will prompt user on every use.
=> #203 Allow localhost selection

docs/CNAME, src/sacn/streamcommon.cpp
Just ignore sync address field
=> Fix #198: Packets with a synchronization address were dropped

src/sacn/sacnlistener.cpp
=> Flag param change and level change on slot count change

deploy.pri
Requires Qt 5.6 or newer.
Fixes issue #216
=> Copy the Windows DLLs to the local bin

src/aboutdialog.cpp, src/addmultidialog.cpp, src/consts.h, src/main.cpp, src/nicselectdialog.cpp, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsender.cpp, src/transmitwindow.cpp, src/universedisplay.cpp, src/universedisplay.h, src/universeview.cpp, src/universeview.h, translations/sACNView_de.ts, translations/sACNView_en.ts, translations/sACNView_es.ts, translations/sACNView_fr.ts
Some general cleanup and minor refactoring
Add a better title to the Universe View subwindows
=> General code cleanup

src/universeview.cpp
=> Merge in changes for a 2.1.3 release

src/consts.h
Resolves primary reason for https://github.com/docsteer/sacnview/issues/187
=> 187 Add a fade rate of 44Hz

src/preferences.cpp, src/preferences.h, src/ui/newversiondialog.cpp, src/ui/newversiondialog.h, ui/newversiondialog.ui
https://github.com/docsteer/sacnview/issues/278
=> 278 Allow user to ignore a version update

translations/sACNView_de.ts, translations/sACNView_en.ts, translations/sACNView_es.ts, translations/sACNView_fr.ts, ui/mdimainwindow.ui, ui/multiuniverse.ui, ui/universeview.ui
Remove invisible "...", update source file paths for new location of *.ui files
=> Update translation ts files

src/ui/preferencesdialog.cpp, translations/sACNView_de.ts, translations/sACNView_en.ts, translations/sACNView_es.ts, translations/sACNView_fr.ts
Fixes #287.
Updates dialog and translations.
=> 287 Fix typo in preferences dialog

src/sacn/ACNShare/tock.cpp, src/sacn/ACNShare/tock.h, src/sacn/e1_11.h, src/sacn/sacndiscovery.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/sacn/sacnsynchronization.cpp, src/sacn/streamcommon.h, src/ui/transmitwindow.cpp, src/ui/transmitwindow.h, ui/transmitwindow.ui
Allow transmit window to set minimum and maximum FPS
Increase resolution of underlying ticker class for sender
Resolves [#156]( https://github.com/docsteer/sacnview/issues/156), [#243]( https://github.com/docsteer/sacnview/issues/243)
=> 243 Feature Request - Transmit View - Manually Set FPS Hz

src/ui/universeview.cpp, themes.pri, themes/darktheme.cpp, themes/darktheme.h, themes/themes.cpp, ui/transmitwindow.ui
Dark theme fixes from v2.1 -> v2.2 and general improvements
=> Dark theme improvements and fixes

src/models/sacndiscoveredsourcelistmodel.cpp, src/models/sacndiscoveredsourcelistmodel.h
Closes issue #313
Add missing bounds check
Add the row instead of resetting the model
Note: Also applied a whitespace change by mistake, sorry about that
=> Fix sACN Discovery

src/models/sacnsourcetablemodel.cpp, src/models/sacnsourcetablemodel.h, src/preferences.cpp, src/preferences.h, src/ui/multiview.cpp, src/ui/multiview.h, src/ui/universeview.cpp, src/ui/universeview.h, src/widgets/gridwidget.cpp, src/widgets/gridwidget.h, src/widgets/universedisplay.cpp, src/widgets/universedisplay.h, ui/multiview.ui, ui/universeview.ui
Add a button to remove sources that have gone offline
Builds on PR #326
=> Clear offline button

CMakeLists.txt, src/models/sacnlistenermodel.cpp, src/models/sacnlistenermodel.h, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsocket.cpp, src/sacn/sacnsocket.h, src/ui/aboutdialog.cpp, src/ui/aboutdialog.h, ui/aboutdialog.ui
If the socket does not bind, keep retrying at BACKGROUND_MERGE intervals
Use a sortable table view in About to show universe listener status.
=> Retry sockets on bind failure

res/pref_display.svg, res/pref_language.svg, res/pref_network.svg, res/pref_recieve.svg, res/pref_transmit.svg, res/resources.qrc, src/main.cpp, src/ui/preferencesdialog.cpp, ui/preferencesdialog.ui
Add categories to the overcrowded preferences dialog.
=> Categorise Preferences
