docsteer/sacnview

src/consts.h, src/multiuniverse.cpp, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/snapshot.cpp, src/transmitwindow.cpp, ui/preferencesdialog.ui, ui/transmitwindow.ui
A Default transmit source name can be added from the preferences dialog.
This is utilised in full by the transmit window and used as a basis for the multiuniverse and snapshot windows.
=> Added option for default transmit source name

src/sacn/sacnlistener.cpp, src/sacn/streamingacn.cpp
Alternate Startcode “DD” per-address stipulates that an address priority of 0 is unpatched. 
So don't merge addresses at priority 0.
=> Treat per-address priority 0 as unpatched

src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnuniverselistmodel.cpp, src/sacn/sacnuniverselistmodel.h, src/universeview.cpp, src/universeview.h, ui/preferencesdialog.ui
It's valid for a source to only send a 0xdd packet for a universe and not 0x00.
Display these appropriately and as required by preferences
=> Display sources that only send 0xdd

.travis.yml
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to a temporary download URL on transfer.sh (available for 14 days). The download URL is toward the end of each Travis CI build log of each build (see below for how to set up automatic uploading to your GitHub Releases page).
For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so.
__Please note:__ Instead of storing AppImage builds temporarily for 14 days each on transfer.sh, you could use GitHub Releases to store the binaries permanently. This way, they would be visible on the Releases page of your …
=> Generate AppImage on Travis CI and upload

src/mdimainwindow.cpp, src/mdimainwindow.h
If the selected row is about to be removed, de-select
Another symptom relating in part to #68
=> Clear row if about to be removed

src/transmitwindow.cpp
Values above 127 wouldn't recall on presets
=> Signing issue with preset recalls

sACNView.pro
By default, the architecture is included in the filename. Please don't remove it.
Also, if the environment variable `$VERSION` is present, then `linuxdeployqt` will use it in determining the filename.
=> Include architecture in AppImage filename by using default naming scheme

sACNView.pro
Reverts docsteer/sacnview#85 - wasn't fixed enough, breaks linux build still
=> Revert "Include architecture in AppImage filename by using default naming scheme"

appveyor.yml, install/win/install.nsi, sACNView.pro, src/main.cpp, src/sacn/sacnsocket.cpp, src/versioncheck.cpp
In reference to #63
Creates a Windows XP only binary and installer, with appropriate warnings about IPv6 related bugs.
N.B. IPv6 in Windows XP was an optional extra.
Binaries and installers are created by AppVeyor
=> Windows XP Support (Dual Binary)

appveyor.yml
QT5.10 (and QT5.9.3) is affected by QTBUG-64784
=> Revert of "Update Appveyor QT version to 5.10"

src/commandline.cpp, src/commandline.h, src/transmitwindow.cpp, ui/transmitwindow.ui
Fixes:
- x [FULL]
- w [THRU] x [AND] y [THRU] z
- x [THRU] y, where x > y
Adds:
- x [AT][AT]
- [Clear][Clear]
- [And] (Recalls previous selection)
Strings are translatable
=> Command line fixes and improvements

src/snapshot.cpp, src/snapshot.h, ui/snapshot.ui
There are times in sACNView when one accidentally stops a running snapshot, and there's no easy way to restore the previous look. Added a "replay" button (which could use a better icon) that appears if someone stops a snapshot but hasn't yet recorded a new one. 
Note - because of new 2.1 branch dependencies, I can't build the project at the moment. I did originally test this change against the master branch, so I have reasonable confidence that the fix is fine. :)
=> Added snapshot replay button

sACNView.pro, src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/sacn/e1_11.h, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsender.cpp, src/sacn/sacnsender.h, src/sacn/streamcommon.h, src/sacn/streamingacn.cpp, ui/preferencesdialog.ui
Limit default packet rate to 44pkt/s (Resolves #130)
-Allow user to override packet rate
Reimplemented multiple packets before transmission suppression.
Replaced FOREACH macro with C++11 ranged for in listener
=> E1.31:2016 6.6.2 changes

libs.pri, src/nicselectdialog.cpp, src/pcapplayback.cpp, src/pcapplaybacksender.cpp, src/preferences.cpp, src/preferencesdialog.cpp, src/sacn/fpscounter.cpp, src/sacn/fpscounter.h, src/sacn/sacndiscovery.cpp, src/sacn/sacndiscovery.h, src/sacn/sacneffectengine.cpp, src/sacn/sacnlistener.cpp, src/sacn/sacnlistener.h, src/sacn/sacnsender.cpp, src/sacn/sacnsocket.cpp, src/sacn/sacnsocket.h, src/sacn/streamingacn.cpp, src/sacn/streamingacn.h, src/universeview.cpp
Resolves #179 
Possible and likely cause of #167
The socket backend could receive frames multiple times, while this wouldn't have affected the resultant DMX data, it would affect the source statistics.
The socket arrangement has been altered, in particular multicast frames for display locally are passed internally and not re-received over the wire (Because Windows and Unix handle ip_multicast_loop slightly differently with multi homed machines, so this is simply disabled). Additionally the number of open sockets reduced.
This will require a good amount of testing to prove it's good. I'm unable to test on MacOS!
=> Socket cleanup

sACNView.pro, src/configureperchanpriodlg.cpp, src/configureperchanpriodlg.h, src/grideditwidget.cpp, src/grideditwidget.h, src/gridwidget.cpp, src/gridwidget.h, src/theme/darkstyle.cpp, src/transmitwindow.cpp, src/transmitwindow.h, src/universeview.cpp, src/universeview.h, ui/configureperchanpriodlg.ui, ui/transmitwindow.ui
Create a multi-editable version of the grid widget for editing per-address priorities, and additionally as another way to set levels. Addresses #183
=> Add multi-grid editing

.travis.yml, deploy.pri, install/mac/sign-mac-executable.sh, sACNView.pro
- Remove the mac SDK force (just use what's available)
- Add a post-build code signing step. This uses dedicated environment variables in Travis to contain the certificate and password for the build. If the variables aren't present, it just builds an unsigned version
=> Fix macos build and add code signing

deploy.pri
Fixes the path so will run on default Qt Creator install
Removes deployment of unused OpenGL Soft and ANGLE DLLs
=> Cleanup windeployqt

src/preferences.cpp, src/preferences.h, src/preferencesdialog.cpp, src/sacn/sacnsocket.cpp, ui/preferencesdialog.ui
Adds a preference option for the TTL of multicast datagrams which are sent by the application. It was discovered in a routed system that our TTL of 1(default) was causing traffic not to be routed.
=> Multicast TTL

libs.pri, src/preferences.cpp
Dark for dark theme, light for light theme
Based on CRC32 of source CID to ensure consistent color for a given source on all platforms.
=> 2.2 - Base the color on source CID so does not change each run

src/sacn/ACNShare/CID.cpp
Correct call for big-endian UUID binary data
Fixes #302
=> Use QUuid::toRfc4122()

src/consts.h, src/ui/flickerfinderinfoform.cpp, src/widgets/universedisplay.cpp, src/widgets/universedisplay.h
Don't hardcode the colors, especially white background.
Flicker Finder was almost unusable in Dark Mode!
=> Respect dark mode in Flicker Finder

src/sacn/ACNShare/tock.cpp, src/sacn/streamingacn.cpp
Also ensure only starts underlying QElapsedTimer once
Fixes issue #306
=> Start the Tock in sACNManager constructor

install/win/install.nsi, install/win64/install.nsi
Add optional hook to sign the installer.
Permits fix of Issue #319 
The github action will need to be altered to hook in a secret back end.
Add and remove the firewall rules in the Windows 8.1+ public/private/domain scopes.
Fixes Issue #318
=> Windows Installer firewall rules and signing

.github/workflows/build.yml
The Windows build has been 64bit since Qt 6.2.4 if not earlier.
Update the github action to upload the Win64 installer
=> Windows installer is now 64bit, update path

.gitignore
Qt Creator 13 has started using this temporary folder
=> Add .qtc_clangd/ folder to gitignore

src/ui/preferencesdialog.cpp, src/ui/preferencesdialog.h, ui/preferencesdialog.ui
Change some radio buttons to combobox
Use grid layouts instead of box layouts
=> Cleanup the Preferences dialog

src/preferences.cpp, src/preferences.h, src/ui/universeview.cpp, src/ui/universeview.h, src/widgets/gridwidget.cpp, src/widgets/gridwidget.h, src/widgets/universedisplay.cpp, src/widgets/universedisplay.h, ui/universeview.ui
Allows comparisons between different controllers that are expected to have the same output levels
eg when transferring a show between different consoles using USITT ASCII
Shows both sets of levels
Uses the same colors as the flicker finder
=> Add ability to compare levels between two universes
